spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/np-spring-mvc-demo
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT

logging.level:
  org.apache.kafka: OFF