spring:
  datasource:
    url: ~
    username: np-spring-mvc-demo
    password: ~
  application:
    name: np-spring-mvc-demo
  jackson:
    default-property-inclusion: NON_ABSENT
    deserialization:
      accept-single-value-as-array: true

  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate

  kafka:
    bootstrap-servers: ~
    security:
      protocol: ~
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # https://stackoverflow.com/questions/60570238/is-a-write-to-a-kafka-topic-only-successful-if-write-on-each-partitions-replica
      acks: all
      retries: 2147483647
      properties:
        max.block.ms: 9223372036854775807
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

management:
  metrics:
    tags:
      application: ${spring.application.name}

my:
  homepage: https://www.my-super-site.example.com
  jws:
    id: ~
    public-key: ~
    private-key: ~
