spring:
  datasource:
    url: jdbc:postgresql://db-postgresql-nyc3-93635-do-user-1523363-0.c.db.ondigitalocean.com:25060/np-spring-mvc-demo-staging?serverTimezone=UTC&sslmode=require
    username: np-spring-mvc-demo-staging
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1011974249454-6gq0hr01gqh3cndoqnss5r69tkk2nd84.apps.googleusercontent.com

logging.level:
  org.apache.kafka: OFF

my:
  homepage: https://staging-spring-mvc-demo.naturalprogrammer.com
  oauth2-authentication-success-url: https://staging-spring-mvc-demo.naturalprogrammer.com?userId=%s&resourceToken=%s
  jws:
    id: e0498dad-4f5f-40cf-86e3-2726ec78463d
  jwe:
    id: c00f9459-82cb-48bc-882d-66b3b65258b4
