name: DigitalOcean App Platform Deployment
run-name: ${{ github.actor }} is pushing docker image to DigitalOcean

# 1
on:
  push:
    branches:
      - main

#2
env:
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#3
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      #      - name: Set App Version
      #        run: mvn versions:set -DnewVersion=${{ github.sha }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean test
      # Uncomment this to deploy push image  run: mvn --batch-mode --update-snapshots clean spring-boot:build-image -Dspring-boot.build-image.imageName=registry.digitalocean.com/naturalprogrammer/np-spring-mvc-demo:app
